dist: trusty
matrix: 
  include:
    - laguage: node_js
      node_js:  
        - "12"
      before_script: 
        - cd Ebar-FrontEnd
      script: 
        - npm install
        - npm run build
    - language: java
      jdk: oraclejdk8
      services:
        - mysql
      before_install:
        - cd Ebar-Backend
        - chmod +x mvnw 
        - mysql -u root < bbdd_Travis.sql
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install