dist: trusty
matrix: 
  include:
    - laguage: node_js
      node_js:  
        - "12"
      before_script: 
        - cd Ebar-FrontEnd
      script: 
        - npm install
        - npm run build
    - language: java
      jdk: oraclejdk8
      services:
        - mysql
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      before_install:
        - cd Ebar-Backend
        - chmod +x mvnw 
        - mysql -u root -e 'CREATE DATABASE ebarbbdd;'
        - mysql -u root -e 'CREATE USER 'ebar'@'localhost' IDENTIFIED BY 'ebar';'
        - mysql -u root -e 'GRANT ALL ON ebarbbdd.* TO 'ebar'@'localhost';'
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install